name: CI with Carbon Tracking Test 2 (Docker Container Building)

on:
    pull_request:
    workflow_dispatch:

permissions:
  actions: read
  contents: write
  pull-requests: write
  issues: write

jobs:
    build-container:
        name: Build and push API
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - uses: ./start

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: false
                  file: Dockerfile

            - uses: ./stop
              if: always()
              with:
                  pr-comment: "true"
